# Your workflow name.
name: Deploy to Docker Desktop Kubernetes

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: my-app-image:latest

      - name: Configure Docker CLI
        run: |
          docker context use default

      - name: Deploy to Kubernetes on Docker Desktop
        uses: Azure/k8s-deploy@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          manifests: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: your-deployment-name
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: your-app
              template:
                metadata:
                  labels:
                    app: your-app
                spec:
                  containers:
                  - name: your-container
                    image: your-image-tag:latest
                    ports:
                    - containerPort: 80

